title: Trophées NSI

sections:

  menu:
    type: fields
    fields:
      menu_links:
        type: pages
        label: Entrées du menu
        layout: cards
  brand:
    type: fields
    fields:
      logo:
        type: files
        label: Logo
        max: 1
  footer:
    type: fields
    fields:
      footer_links:
        type: pages
        label : Menu du pied de page
      social_networks:
        label: Réseaux sociaux
        type: structure
        fields:
          type:
            type: select
            label: Plateforme
            options:
              linkedin: linkedIn
              x: X
              facebook: Facebook
              instagram: Instagram
              tiktok: TikTok
              snapchat: Snapchat
              youtube: YouTube
              twitch: twitch
          url:
            type: url
            label: URL du compte
      legals:
        type: text
        label: Mention sur les droits réservés

  allpages:
    headline: Pages du site
    type: pages
    # parent: site.find("artistes")
